# Generated by Django 2.2 on 2021-09-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210909_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downVote_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='post',
            name='upVote_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
